# Generated by Django 3.2.4 on 2021-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='date_of_appointment',
            field=models.DateTimeField(),
        ),
    ]
