# Generated by Django 3.2.4 on 2021-11-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_doctorappointment_date_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='date_of_appointment',
            field=models.DateField(),
        ),
    ]
