# Generated by Django 3.2.4 on 2021-11-05 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_doctorappointment_date_of_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='end_time_of_appointment',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
