# Generated by Django 3.2.4 on 2021-11-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='draft',
            new_name='set_as_draft',
        ),
    ]
