# Generated by Django 3.2.4 on 2021-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_draft_post_set_as_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Mental', 'Mental'), ('Health', 'Health'), ('Heart', 'Heart'), ('Disease', 'Disease'), ('Covid19', 'Covid19'), ('Immunization', 'Immunization')], max_length=20),
        ),
    ]
